version: '3.7'
services:
  postgres:
    image: postgres:9-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: plaintextpassword
    volumes:
      - ./dev:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 2s
      retries: 3
